char KID_intro_1[] = 
                "Cue Helix. AGE: 12 years\n"
                "Born in a world of promises and inspiration, he may or may not have a bright future ahead of him. Who knows?\n"
                "His parents have been convicted of crimes when he was but 5, leaving him to fend for himself with nary a coin.\n"
                "Wandering the streets, he gathered nickels from customers as a street boy that polished shoes with his tongue.\n"
                "He became known as \"The Cleaner\", the boy that would turn all things shiny and sparkly, although he appeared unkempt.\n"
                "At the age of 7, he was approached by a well-mannered barber, who pitied him and offered him a simple part-time job.\n"
                "He accepted and was tasked with cleaning up after every customer, notified by the barber's flip phone given to him.\n"
                "The oriental barbershop was also the barber's house, where he trimmed and stylized haircuts to precise perfection.\n"
                "This barber coerced Helix to engage in a pastime of his, which was human surgery. He said it was good practice for\n"
                "when he actually becomes a surgeon. It also refined his skill as a hairdresser, making him fairly well-known.\n"
                "Helix agreed, hard-pressed for cash, unaware of what the barber would have him do for the next 5 years.";
char KID_intro_2[] =
                "Cue Helix was the sole accomplice of the barber, responsible for cleaning the floors of the barber's house\n"
                "after each surgery. Helix would earn a quarter or two a few streets away from the house licking shoes.\n"
                "If a customer entered the barber's house with licked shoes, Helix would be called and given a bonus.\n"
                "The victim was knocked unconscious with the drug Benzodiazepines and then operated on. The boy helped with\n"
                "all types of tasks, such as repositioning the patient, stopping bleeding, and making small incisions.\n"
                "Cue tried his best to dissuade the barber from performing lethal surgeries. He would often give in to Cue's\n"
                "request, harboring a soft side for Cue. The duo did get closer over the span of hundreds of surgeries.\n"
                "They kindled a father-son relationship. The barber would often invite Cue for dinner or a place to stay\n"
                "if needed, but Cue declined almost always because he wanted to assert his semi-independency. By the way, it\n"
                "wasn't a predatory relationship, just saying. The one time Cue went over, he ate some tasty ramen and slept\n"
                "in a comfy futon for the first time ever.";
char DOC_intro_1[] = 
                "Hayato Arata. AGE: 38 years\n"
                "Raised by his mother after his father was drafted to fight in the war, never to be seen from his family again.\n"
                "Arata's father was a deserter, running from battle after being convinced he wasn't cut out for the horrors of war.\n"
                "He met his end to enemy soldiers anyway after stumbling into their hidden base while fleeing the battleground.\n"
                "The government sought to dissuade soldiers from deserting, so they chose Arata's father as their prime example.\n"
                "He was portrayed to have betrayed his country, as somebody who ran away and still died to war. \"Fight on!\"\n"
                "This phrase, combined with a picture of Arata's father, was the propaganda the country abused whenever a battle was\n" 
                "lost or people doubted the war effort. To further discourage desertions, Arata's mother was fined 36896415 yen\n"
                "after she was tried. The compensation for deserting had to be paid off somehow, even if it meant a life of debt for\n"
                "somebody. As Arata's mother tried to chip at her debt with odd jobs, Arata was passionately trying to be a surgeon.\n"
                "The job paid incredibly well and was in high demand, so months of studying would be worth it in the end.";
char DOC_intro_2[] = 
                "Ultimately, he was a medical genius, the first to propose that DNA could identify past criminals and assist greatly\n"
                "in developing cures for hereditary conditions. However, even so, he was denied a scholarship for a surgery program\n"
                "as the government thought to continue using Arata's family as THE example that acts of desertion are pure evil.\n"
                "Instead, he was awarded a scholarship for a barber program, regarded as more suiting for a traitor's son\n"
                "However, Arata still excelled, devising a way to extract DNA from saliva in only 7 minutes during his studies\n"
                "Dantalion's Spire accepted one customer at a time, promising increased attentiveness and no distractions.\n"
                "Arata would always request his customer to take off his shoes to conform to the shop's customs and rules,\n"
                "where he placed into his DNA contraption for inspection. He claimed to be preparing the tools for the haircut,\n"
                "but Arata would be discerning whether the shoes have been licked. This turned out to be true only about monthly.\n"
                "That customer would be his guinea pig for testing as he searched, played, and experimented with their organs.\n"
                "Arata planned to publish his DNA manifesto after his next breakthrough, sure to land him an opportunity.";
char QUEEN_intro_1[] =
                "Lille Erikson. AGE: 8 years\n"
                "She was born to very wealthy parents, descendants of royals. They cared for her but spoiled her too much.\n"
                "At school, she wasn't popular, mostly because of her condescending attitude and high class nature. Lille loved animals\n"
                "to death. Hamsters and puppies were her favorite pets, of which she had up to 20 at a time. Her family had to move\n"
                "one day because of job complications. Lille was only 5 years old when this happened. As a result, she had to transfer\n"
                "to another school, which meant that she lost all of her friends, which wasn't many, and had to rebuild relationships.\n"
                "One time during recess, Lille was building her own sand castle in the sandbox when a fire ant approached its gate.\n"
                "She was interested in the insect, yet all the other 1st graders scattered when they saw its big bulbous body.\n"
                "Lille found it cute that the ant wanted to help build her castle. Every recess break, Lille would find that her\n"
                "castle was constructing itself, little by little. Other kids stayed far away, disliking bugs and Lille alike.\n"
                "For show and tell, Lille brought her leather suitcase, the one she used to pack when traveling to her new home.\n"
                "That time during recess, Lille scooped the sand castle into her suitcase, along with hundreds of fire ants.\n"
                "Lille's parents paid for it when the teachers noted this. They accepted the generous payment in exchange for sand.";
char QUEEN_intro_2[] = 
                "Lille brought her colony back to her house, also making sure to let the fire ants have access to oxygen. How considerate.\n"
                "She showed her ants to her other pets by unzipping the suitcase's zipper like how a guard opens a gate for passengers.\n"
                "However, the fire ants bit and poisoned the hamsters and puppies, identifying them as the colony's source of food.\n"
                "Lille actually didn't mind the deaths of pets, as she could just purchase some more. However, she couldn't buy fire ants\n"
                "in her country, causing her to treat them as favorites. As her parents continued buying pets for her, she continued to feed\n"
                "them to her ants, who ganged up on the poor animals. Whenever she left the house, Lille carried her beloved suitcase, which\n"
                "contained the ants and their victims. Stray cats and dogs were conditioned to be the ant colony's favorite wildlife prey.\n"
                "Occasionally, when Lille went to a friend's home, she would come across a pet, which she saw as another source of food.\n"
                "Lille's parents compensated for the pets' deaths with cold cash every time, and nobody batted an eye at the dead pet.";
char LORD_intro_1[] =
                "Severino Acquarone. AGE: 50 years\n"
                "He was born to mafia parents of the Affizzioni clan, which exposed him to the criminal universe at a very early age.\n"
                "Initially, he ran chores for the clan, but his role would expand to bodyguard, smuggler, messenger, and info gatherer.\n"
                "The godfather noted how bright Severino was and quickly became one of his favorites. As a result, he climbed the ranks.\n"
                "He was agile, fit, and resilient in fights. Nobody messed with him, allowing him to promote without any opposition.\n"
                "At 32 years old, he was selected as the next boss when the previous godfather was killed by rivaling clan members.\n"
                "Severino was cunning and vicious when violence was needed but also rational and smart about most of his major decisions.\n"
                "He dominated the criminal competition by focusing on the transportation and selling of alcohol and drugs, netting him\n"
                "a reputation as a ruthless drug lord. As such, he was the target of many hitmen and law enforcement units, but his\n"
                "intuition and abilities always gave him the upper hand in encounters. Severino didn't mind the law enforcement units\n"
                "because they accept bribes and were dangerous. If you even showed intent to kill them, they would gather up and hunt you.";
char LORD_intro_2[] =
                "Even so, he despised law enforcement units for arresting and \"accidentally\" killing criminals and innocents alike.\n"
                "If push came to shove, he wouldn't hesitate to give them the beating of their lives. They usually left him alone though\n"
                "because they had constant surveillance of his moves. It was like a glorified unspoken contract between the two parties.\n"
                "However, if he commited a horrible deed, then this peace would most likely be put down. That's how our relationship works.\n"
                "Any person that approached him to eliminate him for good was inevitably beaten in combat. You don't mess with this guy.\n"
                "Afterward, Severino, always armed with bottles of liquor hidden in his suit, would forcefully pour alcohol down their\n"
                "throats until they died to lethal blood alcohol concentration levels. Severino often went on contracts, meetings, or\n"
                "sale opportunities by himself. Severino was confident that he would win any fight thrown at him. This habit of his also\n"
                "made him well liked by his people. He shows that he isn't afraid of anybody and for good reason.";
char STOWAWAY_intro_1[] = 
                "Nemo Gilliam. AGE: 26 years\n"
                "His father was a lowly pirate in a crew of 20, while his mother was the wife of the crew's captain.\n"
                "Nemo's mother died upon birth. Despite his wife's death, the captain maintained his carefree attitude and allowed\n"
                "Nemo's father to stay with the crew even though he KNEW. Nemo was tasked with stealing the crew's treasures every once\n"
                "in a while, so as to test Nemo's devotion to his father. As it turned out, Nemo had a knack for stealing and hiding.\n"
                "This kleptomaniac could stuff large diamonds and bars of gold into his handbag without anyone noticing him doing so.\n"
                "At first, Nemo swam all the way back to his house after each theft, analyzing the stars' alignments to direct him.\n"
                "Eventually, on longer expeditions, Nemo just lurked around and waited until the ship returned to the village.\n"
                "Nemo would stash the treasures into his room, only taking some out when his father needed proof of his loyalty.\n"
                "Truthfully, Nemo's father was being awarded a smaller portion of the riches in salary than the others as punishment.\n"
                "Rumors of a crew member stealing from the stash rose. The captain suspected Nemo's father was the thief in question.\n"
                "One expedition, Nemo was sitting in the shadows when he witnessed the captain fall an axe on his father's forehead.";
char STOWAWAY_intro_2[] = 
                "At the early age of 15, little Nemo watched on with horror, unsure of what to do. For the next year, he stole only\n"
                "from the neighboring villages. When he was 16, Nemo heard his father's voice again, but it was ringing in his head.\n"
                "The voice simply told him to get revenge. \"Kill them all for me\". Nemo felt that he had to follow his orders.\n"
                "He didn't kill them directly. Instead, Nemo kept stealing from their stash raid after raid. One after one, Nemo\n"
                "witnessed the unstable captain strike, slice, and stab another crewmate. His brain had turned to mush after\n"
                "his wife cheated on him with Nemo's father. Prior, he was carefree and caring to everyone. \"Don't wait, just kill him!\"\n"
                "As the captain's last faithful crew member fell, Nemo robotically followed his father's command. He went in and\n"
                "faithful to his father, chopped the captain. Since then, Nemo's escaped from crime after crime, known to become\n"
                "invisible when stealing. We estimate that he's stolen over 20,000 treasured possessions. He hasn't murdered anyone else.\n"
                "Among these are smart fridges, championship trophies, rare collectibles, aged liquor, and a diver's mask.\n"
                "These are all items that were targeted by Nemo's father.";
char LUNCHLADY_intro_1[] =
                "Lexa Miller. AGE: 33 years\n"
                "She's been a lunchlady for about 12 years now, serving and cooking high school students their hot lunch meals. Before\n"
                "that, she was a head chef at a prominent homeless shelter. Serving there did wonders for her mental health because\n"
                "she enjoyed helping the hungry and liked the type of men that frequented there. She courted many homeless men there.\n"
                "In fact, she met her future husband there, Cadan Smith, a homeless man who was soft-spoken but physically strong.\n"
                "Soon after, Lexa married Smith and started working as a certified lunch lady to help support her family. They had\n"
                "spoken and dated for only a few months, but the relationship seemed unbreakable and future-proof to little old Lexa.\n"
                "Anyway, working at a neighborhood school was also a pleasant experience, as the students would usually be happy with the\n"
                "lunch program. In elementary school, the kids had to bring their own lunches, so now, they're offered lunches at no cost.\n"
                "Getting back on track, the Smith family lived peacefully and well for 3 years, with Lexa providing for her family.\n"
                "Smith was training everyday to be a professional boxer or so, he claimed. His body apparently needed even more toning.\n"
                "When she was 24 years old, Lexa gave birth to her only daughter. Moments later, Smith announced that he was\n"
                "leaving Lexa for good. He snatched his daughter up and left the hospital after snatching the birth certificate.";
char LUNCHLADY_intro_2[] =
                "Lexa was beet red with anger, but the sudden divorce caused Lexa to believe that the daughter was the problem.\n"
                "Back at school, Lexa would propose to ask to see the students' ID before giving them their lunch. She argued that\n"
                "this was more efficient than having a student grab a lunch just to tell the ID checker they didn't have their card.\n"
                "Any girls that had \"Smith\" as their surname was poisoned by Lexa. Sometimes she sprinkled a bit of arsenic. This was\n"
                "regardless of their age. She didn't count the years that Smith left her. All she knew was that she wanted to live\n"
                "to end his family name; any kids Ewan had would have to be wiped from the face of this planet. She wouldn't allow him\n"
                "happily with kids that weren't hers. The unknown daughter had to die as well because she was HIS daughter, not HERS.\n"
                "Sometimes she used additives that contained iodine, ammonium nitrate, or lead. She spent the money that she would\n"
                "have spent on her family to buy these chemicals and substances. She never learned what her daughter's first name was.\n"
                "Lexa moved from school to school when she felt that the school's staff members were suspicious of her behavior.\n"
                "Once again, she took on a part-time job as a homeless shelter chef again, hoping to meet Ewan Smith or another man\n"
                "that would make her a happy woman.";
char ARSONIST_intro_1[] =
                "Inigo Fernandez. AGE: 47 years\n"
                "He was raised up in an orphanage. He was quiet and said to have been very creative in his homework answers.\n"
                "Reticent and introverted, Inigo studied in his free time, hoping to be able to share his knowledge with the others,\n"
                "netting him a few friends. Compared to the other kids, he was much more informed about the outside world's goings-on.\n"
                "His listening skills were fine-tuned, and he also acquired bits and pieces of knowledge about the nature of fires in\n"
                "his studies. Later on, Inigo would use this knowledge to showcase his abilities to the world and his country.\n"
                "Professionally known as the \"Muckraker\" to his affiliates, Inigo became a spy, private investigator, and arsonist.\n"
                "During the war, he saw his chance to make it big. He is known for sabotaging enemy bases, setting shipdocks ablaze,\n"
                "and shortening the war by upwards of 3 years. Prime targets were the enemy's navy and supply bases, which he managed\n"
                "to encroach on with the help of double agents. He had a toolbox of fire items disguised as electronic components.";
char ARSONIST_intro_2[] = 
                "He used molotovs, accelerants, cigarettes, and other firebombs to burn down buildings occupied by the enemy forces.\n"
                "Inigo was never caught by the enemy, only attacking during times of hysteria when minimal witnesses were present.\n"
                "After the war ended, Inigo was awarded a medal for his bravery and contribution to his country, making him a hero.\n"
                "He was only 21 years old, but the fame helped Inigo open up a bit more in terms of his personality and business.\n"
                "He turned to a life as a private investigator, offering his arsonist services in the underworld, burning down\n"
                "locations that he deemed a threat to the country. This could be a killer's house or a lonely location that housed\n"
                "a threatening person. On another case, Inigo set a crime scene ablaze for a suspect because he believed they were\n"
                "innocent, incapable of commiting the misdeed. These suspects were usually children, old friends, or former comrades.\n"
                "Other times, he would expertly trail his target, reporting to his client about his findings. In these cases, the\n"
                "person he was trailing seemed mostly innocent.";
char FRAUDSTER_intro_1[] =
                "Dalia Fortuna. AGE: 15 years\n"
                "She grew up being the eldest sibling of her two sisters. Dalia attended elementary school, where her fondness of\n"
                "trading cards blossomed. Card series were based off of fictional creatures; they were very popular with kids.\n"
                "Dalia couldn't afford any cards, so she struck a deal with students that owned cards. She would often challenge\n"
                "them to a game of Rock Paper Scissors. If she won, a card she chose would be hers. If she lost, she would have to owe\n"
                "them $10, a lot for 4th graders. Alternating between wins and losses, Dalia would ultimately compile her first deck\n"
                "at the cost of owing a combined $500 to classmates. When they asked for their favors, Dalia would have to admit she\n"
                "couldn't pay them back yet. She earned $500 back when she won a tournament using that very same deck, which she used to\n"
                "clear her favors owed. Her opponents attributed this victory to her deck composition and devotion to the card game.\n"
                "Dalia would be absorbed in the game, referencing it frequently in casual conversations.";
char FRAUDSTER_intro_2[] =
                "Dalia's favorite card was *Fortuna*, a goddess that brought good or bad luck to people. This was partly due to her\n"
                "sharing the same name. The other reason was because of the random factor that she brought to the card battle, able to\n"
                "grant any of 22 effects depending on a die roll; 7 were beneficial, 7 were harmful, and 8 affected both players.\n"
                "One day, Dalia enthusiastically set up the \"Fortuna Shrine\", which was both a service provider and place of worship.\n"
                "She would always practice her die rolling skills at the shrine. She also offered a fortune telling session, where a\n"
                "prediction of the client's future would be told via a colorful spinning wheel with cryptic symbols and characters.\n"
                "Sessions were $15 each and involved Dalia spinning the wheel. The resulting symbol or character that the wheel landed on\n"
                "would dictate the client's fate. She had 2 to 3 clients initially, but others started piling in to learn their fate.\n"
                "Dalia would assert that their fates were her best guesses. She guessed based on likelihood, mood, and the number of\n"
                "times her client requested a fortune telling. For example, a 14 year old classmate requested the fate of his love life.\n"
                "\"Oh, I see. Fortuna whispered it to me. You will go through 7 girlfriends until your soulmate pops up in your life!\n"
                "She'd be perfect for your future self, I'm sure!\" Translucent fates like these would usually be told. She would also\n"
                "challenge her clients to a card duel for up to $500 per win. This would only be when she got better at rolling the die.";
char FRAUDSTER_intro_3[] =
                "Dalia acquired quite the fortune over the years from this business. She would redistribute the wealth to her siblings or\n"
                "clients that seemed depressed or had bad fates. Dalia managed well, using the wealth on personal needs only when\n"
                "necessary. Some clients expressed their doubts but were quieted by clients who supported the Fortuna Shrine.\n"
                "With all those years of practicing her die rolling, she managed to get a beneficial roll almost always. She revisited\n"
                "the card game's competitive scene and her opponents literally got rolled on. Tournament organizers saw no reason\n"
                "to ban cards that had random effects because of all the other random aspects in the game, such as drawing cards or\n"
                "acquiring cards through booster packs. Dalia had yet to see the holographic *Fortuna* card, which was the last\n"
                "major component she thought the Fortuna Shrine needed. She would continue her fortune telling and tournament runs,\n"
                "using money she got from tournaments to try to get a holographic *Fortuna* from card packs. The chances of getting it\n"
                "are ridiculously near zero though. It wasn't like 1 in 36 packs or anything like that. More like... 1 in 360000 packs.";
char NAPPER_intro_1[] =
                "Lucinda Ramos. AGE: 45 years\n"
                "Her mother died from giving birth. At an early age of 15, she became a prostitute in order to provide for herself.\n"
                "The gang she was involved with was nationwide and had many supporters. There would be hideouts near every large city.\n"
                "Lucinda stopped being a prostitute when many of her daughters matured. She would hence be promoted to delivery girl.\n"
                "The delivery girl would drive prostitutes to very important clients safely or transport classified objects to hideouts.\n"
                "Another task of hers was to hunt and bag vulnerable victims. At a glance, she would categorize the potential target.\n"
                "\"Frail? Alone? Young?\" If all of these questions yielded a \"yes\", then a plan would be constructed as a trap.\n"
                "She had tricks up her sleeve. One of them exploited the target's goodness and hospitality to strangers on the road.\n"
                "The vehicle provided to her by the gang was a used car that frequently broke down due to battery or overheating problems.\n"
                "If she so happened to have her car break down during the trip, she would search for a victim following her guidelines.\n"
                "An eerily realistic looking baby doll was always in the back seat. Their eyes appeared closed, their skin soft.\n"
                "She believed that cradling the baby doll would help lure victims, especialy women.";
char NAPPER_intro_2[] =
                "Sometimes, she would flag down a passing vehicle for assistance. Other times, goody two-shoes would approach her.\n"
                "The time she used to converse with them was when she would judge her target and check off boxes in her head. Easy victim\n"
                "If the target offered to repair the vehicle, Lucinda would accept. Other times, the target would offer a drive\n"
                "to where help could be received. She also accepted these attempts. She would convince the target to bring her to their\n"
                "home, including the prostitute in the backseat. The prostitute was always young enough to be Lucinda's daughter,\n"
                "and usually, they WERE her daughters, as they were the most popular in the gang. To outsiders, Lucinda appeared\n"
                "to be a mother heading out of town. People that have fallen for this ploy would fall for her other lies as well.\n"
                "After an analysis of the situation, Lucinda would report to the gang's communications manager via phone, who would\n"
                "alert gang members near her to close the deal. By this point, Lucinda had mapped out the interior of the home and\n"
                "considered the means of defense the target had. When the cavalry came, the target would be overwhelmed and transported\n"
                "back with the gang members. Lucinda and the prostitute would trek all the way back to the old car after getting the\n"
                "correct tools to fix the vehicle in the town.";
char NAPPER_intro_3[] =
                "This was an example of the perfect trafficking scheme. Often times, the target wouldn't fall for such an act. Then,\n"
                "Lucinda's move would be to isolate them and alert the manager OR to just get their help and wait for the next breakdown.\n"
                "After a successful delivery, Lucinda would be rewarded with just enough money to provide for all of her children.\n"
                "Meanwhile, the prostitute would be \"put to work\" until a satisfactory result was obtained, then returned at some point.\n"
                "Having Lucinda deliver items or people would be cheaper and more efficient than allocating gang members to transport\n"
                "the same things, so she would travel for up to 16 hours everyday. Unfortunately, she was given no free days ever, so\n"
                "it was when she had to drive one of her kids that she would give them their share of the money. They would accept the\n"
                "wad of cash stoically. It was just another excuse to keep living for them. You should definitely appreciate the people\n"
                "that care and provide for you, just telling the truth here. Anyway, Lucinda was one of many transporters in the country\n"
                "where the gang was based. Eventually, the gang expanded to other countries nearby and the business would thrive.";
char BAT_intro_1[] =
                "Grischa Panchenko. AGE: 30 years.\n"
                "He has accomplished skills in electrical engineering, biotechnology, computer programming, and aircraft systems,\n"
                "teaching himself everyday since he learned to read. When his parents bought him a brand new car as a gift, he asked\n"
                "them to return it and get him a van instead. They agreed, as this was Grischa's high school graduation present, and\n"
                "so, he got his van. Inspired by the BatComputer in the Batman universe, Grischa modified his van into a mobile unit\n"
                "that could investigate events from afar. Computers, drone charging stations, hidden pinhole cameras, and wifi were\n"
                "installed in the trunk. He planned to use the van as his center of operation for publishing cinematic videos of the\n"
                "world around him on the internet. Grischa soon enrolled into a college thousands of kilometers away from his house.\n"
                "Often, when he was done with coursework for the day, he would take his van, now named the \"Grimobile\", out for\n"
                "a spin. Videos of the campus's sheer activity and special events would be filmed by his remote-controlled drones.\n"
                "At night, he would go to his van for private time, studying for exams, reading books, or watching videos online.\n"
                "He'd rarely record videos at night because parties were the only events happening at these times, which didn't\n"
                "interest him at the time.";
char BAT_intro_2[] =
                "Grischa enjoyed watching new Batman movies, pornographic films, and news channels. He only became interested in\n"
                "parties when the host of the hacking party mentioned they had the newest Batman movie leaked. Thus, Grischa attended\n"
                "the hacking party with hundreds of other students to watch the latest Batman title. It was an incredibly entry, and\n"
                "just about everybody at the party enjoyed the movie. After the movie, the partiers began mingling, drinking,\n"
                ", dancing, playing games, copying homework, and having fun. It was time for Grischa to leave. He had seen everything.\n"
                "He left the party and noticed a sizeable crowd nearby, presumably a group of partiers that left. Grischa decided to\n"
                "check the scene out with his own eyes instead of a drone's camera because of how close he was to the gathering.\n"
                "There, he witnessed a young woman engaging in sexual intercourse with a young man. However, the woman was crying and\n"
                "asking for help from the crowd of students taking videos of the scene. Grischa was traumatized by the expression made\n"
                "by the violated woman. It was like a face of one of the Joker's victims when the Joker tortured and abused them.\n"
                "Looking closer, the man's face had a grin that rivaled that of the Joker's. Grischa thought to confront the man, but\n"
                "he decided against it, what with all the other bystanders. The image of the scene would forever stay in his mind.\n"
                "Since then, he would indulge in videos at night until one of his courses covered night vision systems, which allowed\n"
                "him to install technology on his drones that enabled better imaging.";
char BAT_intro_3[] =
                "Once installed, Grischa would survey the night with his upgraded drones. He thought that if college parties happened\n"
                "frequently, then rapes would happen frequently. He wanted to confirm his line of thinking with hard evidence and\n"
                "rid himself of his trauma. Grischa saw another young man engaging in sexual intercourse with a woman in an alley\n"
                "through his drone. Listening in on the audio confirmed his suspicion of the man being a rapist. The faces weren't as\n"
                "horrific as the first time though. Grischa mustered his courage and donned his Batman outfit, as well as equipping his\n"
                "custom-made batarangs, boomerangs shaped like bats. He would drive near the scene of the rape, monitoring video feed\n"
                "to make sure the rapist was still there. First, he recalled his drone to recharge it. Then, he set off to confront\n"
                "the rapist and his trauma. \"Stop your doing, villain!\" BANG! The batarang slammed into the rapist's body before\n"
                "returning to its owner. During this surprise attack, Grischa would tell the rape victim to flee the crime scene as\n"
                "it would soon get messy. He would threaten him if he didn't follow his orders, using video evidence on his phone\n"
                "through the cloud as blackmail. What Grischa did afterward was reckless and powerful.";
char BAT_intro_4[] =
                "Grischa would proceed to rape the initial rapist, but he didn't have a huge grin on his face like the first rapist.\n"
                "Instead, he asked the rapist if they liked it, to have a taste of their own medicine. The rapist was confused and\n"
                "genuinely terrorized. After this, Grischa left the alley and anonymously filed a report to the law enforcement units,\n"
                "sending video evidence, locations, and facial data to them so that the culprit would be found. Rapists that have\n"
                "reported that a man with a Batman mask raped them have been ignored due to lack of evidence. Grischa would continue\n"
                "this, trying to convert rapists into better human beings, while developing new gadgets to help him reach this goal.\n"
                "To rape victims he saved, he was known as \"The Caped Crusader\", but to rapists, he was known as \"The Dark Knight\".\n"
                "As for his tools, his drones have rarely been identified on site due to their black paint and quietness. He also has\n"
                "developed a miniature taser device on his gauntlet for when his victim puts up a fight against him. It's designed to\n"
                "paralyze the average human for a few minutes with a concentrated shock.";
char ASSASSIN_intro_1[] =
                "Matilda Walker. AGE: 22 years.\n"
                "She was born into a family that consisted of the assassin father, hacker mother, and trainee son. The family resided\n"
                "on an island bordering the main country. The parents were associated with the government, tasked with taking out\n"
                "undesirables and political targets for hundreds of thousands of dollars. They owned a private jet and a whole armory.\n"
                "Years following Matilda's birth, the Walker parents were trying to prepare their kids to take over the family business.\n"
                "At first, the parents trained the 5 year-old Matilda as a hacker, but she claimed that what her brother was learning\n"
                "was way more appealing. The ever so wholesome parents decided to teach Matilda the ways of the assassin because of her\n"
                "innate interest. This meant that her brother's curriculum changed to the ways of the hacker, taught by the mother.\n"
                "Matilda had shown a weird fascination with the concept of death when explained to her. She would pester her parents to\n"
                "give her her first contract. Only when she was 16 years old did they think she was finally ready for her first mark.\n"
                "The assassin Matilda and her hacker brother were tasked with eliminating a political figure that handled casino bribes\n"
                "in a large scandal. The government saw it fit for this figure to be ousted entirely.";
char ASSASSIN_intro_2[] =
                "The hacker brother would attempt to obtain useful information on the mark, such as upcoming plans or whereabouts.\n"
                "After assembling a plan, Matilda would fly out on the jet and begin to claim the mark. This time, the duo figured\n"
                "out a time when the politician would be alone in his apartment room. Matilda managed to sneak inside with the help\n"
                "of her expert climbing skills. Once inside, she snuck into the bathroom's utility closet, thinking of the next step\n"
                "in their plan. This was the killing: how would she make it SEEM like the target accidentally killed themselves?\n"
                "See, it was more professional and efficient to create this illusion. A seemingly accidental death usually warrants\n"
                "a smaller investigation and less publicization. Plus, it was more fun this way, like it was a trial of creativity.\n"
                "Matilda thought while the politician entered the bathroom, opened the shower door, and turned the shower on. However,\n"
                "the politician closed the door and left the bathroom. It was obvious now: the shower took a good amount of time for\n"
                "the water to get hot. Matilda crept up to the shower door, opened it, and put the 3 bars of soap around the shower's\n"
                "floor, hoping the politician would slip and collide his head with the metallic shower shelf. The water would make\n"
                "the surface a slippery hazard, and if the politician was only knocked unconscious by the collision, the shower would\n"
                "eventually scald him for a continuous period.";
char ASSASSIN_intro_3[] =
                "The plan worked. Miraculously, the politician slipped on the surface as Matilda hid in the utility closet again.\n"
                "All she had to do was confirm the kill, which she did. Short afterward, she evacuated the room and returned home.\n"
                "Her parents praised her when news channels reported the politician's accidental death. That was her first mark in\n"
                "the family business out of hundreds. Eventually, the Walker parents retired and passed away, passing the baton to\n"
                "their children. The duo continued the legacy, assassinating as per the government's orders. It was the same deal\n"
                "for every mark; the hacker brother would provide information, and Matilda would find a way to eliminate the target\n"
                "in a manner that made the death seem accidental. At around 50 marks, they were confident in their abilities\n"
                "Whenever there was a huge period when they had no target, the duo would desire some semblance of entertainment.\n"
                "For Matilda, that involved death and the psychology around it. Her brother just wanted amusement in their lives.\n"
                "The Walkers bought out a private island for this purpose, which would become the scene for their game.";
char ASSASSIN_intro_4[] =
                "The game featured 15-20 people who would compete in the game for the spot of \"last one alive on the island\".\n"
                "The players were picked by Matilda, who unprofessionally flew to large cities to advertise a \"tournament that\n"
                "offered a grand prize of granting any practical wish\". The prerequisites to compete were that \"you must have no\n"
                "loved ones and you must be strong\". The hacker brother would confirm the former requirement while Matilda decided\n"
                "on the latter one. People that wanted to compete and fulfilled the prequisites flew by jet to the private island.\n"
                "The brother would make sure that the contestants had nourishment and a place to sleep while waiting for the game.\n"
                "The game would be announced and explained when all the contestants were assembled. A few weapons from the armory\n"
                "were scattered about the island. Anybody that tried to escape the island was sniped by the hacker brother.\n"
                "When no action was happening or the contestants seemed to be stalling, Matilda took her guns and shot down some\n"
                "players as a warning. The contestants were free to continue sleeping in the hall or eat in the hall but that would\n"
                "make them vulnerable. The winner would be asked for their wish, and wishes that could be granted would be granted.\n"
                "You could wish for money, the duo to assassinate somebody, a car, information on somebody, death, and more!";
char HACKER_intro_1[] =
                "Lachlan Walker. AGE: 28 years.\n"
                "He was the first-born of the Walker family. Lachlan grew up sheltered and pampered by his parents, who gave him\n"
                "plenty of love. The island was isolated from the mainland, so he didn't have any friends or anything like that.\n"
                "Instead, he spent his childhood exploring the island and practicing swimming. Lachlan was fond of animals, often\n"
                "spying on them for fun. Insects resided on the island, and birds frequented during specific seasons of the year.\n"
                "Matilda was born when Lachlan was 1 year into his training, accomplished in marksmanship and communications.\n"
                "Lachlan improved his skills in handling firearms and was left to practice his aim by himself. Soon, he experienced\n"
                "a rivalry with his sister, who was receiving increased affection from his parents. Meanwhile, he was left with\n"
                "rigorous coaching and self-teaching time, especially when his parents were on a mission. One time during training,\n"
                "Lachlan noticed a cattle egret, a type of heron, lay three eggs in its nest. Days of training and incubation passed\n"
                "by until the eggs finally hatched. The chicks fought for food amongst each other, and the end result was the older\n"
                "chicks ganging up on the youngest chick so that there'd be one less mouth for their parents to feed.";
char HACKER_intro_2[] =
                "It was then that Lachlan had an idea. Just use your assassination abilities to kill your sister, simple as that.\n"
                "He pointed his sniper rifle at his sibling with malicious intentions and shot. The 4 year-old Matilda performed a\n"
                "spectacular backflip to dodge the bullet that slashed through the air. She followed up with an incredible somersault\n"
                "to dodge the next one. The next bullet completely whiffed as Lachlan trembled with anger. He gave up on siblicide\n"
                "to free himself of further humiliation. When Matilda was 5, she told the Walker parents that she wanted to study\n"
                "whatever Lachlan was training for. This would fuel the unrequited competition even more, especially when Matilda\n"
                "turned out to be gifted in the ways of the assassin. Lachlan was taught how to hack federal networks, intercept\n"
                "traffic flow, and leave no trace by his hacker mother. During this time, he was happy again, getting attention\n"
                "from one of his loved ones. Inevitably, that love would cease when he had homework to do, like hacking a network for\n"
                "some piece of information. He spent entire days hacking and programming in his room while Matilda was showered with\n"
                "lessons that she aced in no time.";
char HACKER_intro_3[] =
                "The last lesson he was taught was \"to learn from every single crack\", which he took to heart. This was shortly\n"
                "before the Walker parents died to natural causes. Since then, he has treated hacking networks as a means of acquiring\n"
                "new information about the outside world. His sister has claimed the private jet as \"hers to use\" and goes to the\n"
                "mainland every now and then for her amusement. Lachlan spends his days researching networks, gathering news about\n"
                "conspiracies and dark web goings-on. To prepare for missions, Lachlan probes into many networks to try to gain\n"
                "important information about the target Matilda is to assassinate. He still harbors a grudge against her and tries\n"
                "occasionally to outwit her with a murderous intent, always failing. Matilda isn't bothered by this, finding it\n"
                "to be a fun test. As for the game that the duo hosts, Lachlan is tasked with keeping an eye over the contestants,\n"
                "sniping any deserters and tranquilizing contestants when it's time to sleep. When he had free time, he would hack\n"
                "away in his room, which was on the topmost floor of the lobby building, where he could assist with any marks and\n"
                "have a bird's-eye view of the entire island.";
char HACKER_intro_4[] =
                "Lachlan didn't come up with the game idea. He only assisted with making the rules for the game. The first rule is\n"
                "\"you must have no loved ones\" to compete in the game. By hacking networks that contained personal information,\n"
                "he was able to compile information that related to this. He made an assumption based on his experience and findings,\n"
                "which wasn't always accurate; bosses, parents, and significant others were always considered \"loved ones\". As for\n"
                "the reason behind this condition, Lachlan thought that having nobody close to the competitor meant a smaller chance\n"
                "of the competitor making it on a missing persons search. Having no loved ones also implied that the competitor had\n"
                "less of a reason to live, rendering them less fearful of death and the game. That was essentially his reasoning.\n"
                "The second rule is \"you must be strong\", at least in the eyes of Matilda. This way, Matilda could be entertained\n"
                "even more by the competitors killing each other. Secretly, he wanted to team up with a strong competitor and finally\n"
                "get rid of his sister. The third rule is \"you must stay on the island until the game is finished\". The punishment\n"
                "for breaking this rule is a bullet to the dome. This discouraged competitors from running away and telling folks\n"
                "about the game. It was also the best practice he could get on using a sniper rifle.";
char FERAL_intro_1[] =
                "Chike Sabra. AGE: 17 years.\n"
                "He was born during wartime. His father fought in the war but was killed in action. In response, Chike's mother\n"
                "hanged herself when Chike was only 5 years old. His village was compact and busy with supporting the wartime, so\n"
                "nobody paid any attention to lonely Chike. He spent days crying rivers, bothering neighbors for food with no\n"
                "success, and daydreaming. Eventually, his hunger clouded his mind, and he wandered into the wild jungle in search\n"
                "of edibles. There, he befriended greater spot-nosed monkeys and lived with them for many years. He helped groom\n"
                "them and they helped groom him; it was a mutualistic relationship through and through. The monkey group taught\n"
                "Chike their communicative methods, which consisted of screeches, chirps, staring, and sniffing. And so, he lived\n"
                "on seeds, fruits, and insects in the jungle. Chike was a capable forager for the monkey group, able to leap\n"
                "across trees to access sources of food just like the monkeys could. Additionally, he was a decent lookout, capable\n"
                "of spotting predators from long distances away and then relaying the information through the monkey language.";
char FERAL_intro_2[] =
                "The one task that Chike wasn't adept at was raiding the crops of humans. It wasn't because he felt bad doing it.\n"
                "It was because Chike disliked humans, which arose due to his experience as a villager child. Yes, food was scarce,\n"
                "and yes, the villagers were occupied with orders from the warring government, but couldn't they help him just\n"
                "a tad bit? That was what Chike thought about his kind, so when the villagers encroached on the jungle to secure\n"
                "more supplies for the war effort, Chike was furious. They didn't do anything to help him, and now, the village\n"
                "seeks to harm his wellbeing even more. The monkey raids on farms was a huge setback to the village's production.\n"
                "The government constantly demands supplies from them like there was some quota to meet. Ultimately, the villagers\n"
                "chose to kill three birds in one stone by entering the wild jungle with pitchforks in hand. First, they would\n"
                "get rid of the greater spot-nosed monkeys, preventing them from stealing crops. Second, they would have a fresh\n"
                "supply of bushmeat, meat from wildlife species that provided protein. Third, the jungle's fruits, nuts, and seeds\n"
                "could be scavenged with less difficulty.";
char FERAL_intro_3[] =
                "As the first few of the greater spot-nosed monkeys were shot, Chike built traps out of leaves and fibers. He concealed\n"
                "himself and ensnared a young villager in his makeshift net. While the villager was busy trying to get out, Chike grabbed\n"
                "the gun that fell to the ground. Note that he doesn't know how to fire the gun, so he wielded it like a polearm instead.\n"
                "Hiding behind trees and in bushes, Chike would ambush any passers-by and rough them up. No villager knew the jungle\n"
                "like Chike did; they were far outmatched in guerrilla warfare and forced to retreat from one teenager and his multitude\n"
                "of traps. The villagers were exhausted and demoralized from fighting in the war, fighting in the jungle, and fighting\n"
                "amongst themselved for a morsel of food. This was famine from the government milking the villages' supplies. Surrounded\n"
                "by the jungle that Chike controlled, the last resort was eating the flesh of the dead villagers. But it didn't matter\n"
                "because months later, a raid by enemy forces would burn the village to the ground. Greater spot-nosed monkeys became\n"
                "critically endangered, and none could be found in the jungles that Chike dwelled in. Years after the war, Matilda\n"
                "found Chike alone in the remains of the jungle. Chike tried to ambush her, but she swiftly dodged all of his attacks\n" 
                "while explaining the criteria for the game. Chike understood bits and parts of what she was saying. He accepted the\n"
                "invitation after she mentioned \"a wish for any dream you want\".";
char ARTIST_intro_1[] =
                "Faiza Chaudhary. Age: 21\n"
                "She was born as an only child. Faiza was raised strictly, as her parents wanted her to be successful in life. This\n"
                "meant extracurriculars galore, frequent studying, restricted leisure time, and most important of all, heavy monitoring.\n"
                "Their daughter met their expectations. She aced all of her classes, avoided parties, and had leadership positions.\n"
                "Student council, chess team, gymnastics team, calculus and physics class, and English. She had them all under her thumb.\n"
                "Although Faiza loved her parents and all, she didn't want to be under their control like a measly pawn. Secretly, she was\n"
                "interested in art, which allowed her to indirectly convey her concealed emotions and feelings. Instead of paying attention\n"
                "in class, she would occupy herself by doodling on loose leaf paper. Every doodle evolved her emotions, showing its strain\n"
                "when art styles, themes, and colors changed drastically. Her parents kept telling her \"to just work harder and one day it\n"
                "will pay off\". Faiza became more and more skeptical of this claim as she tried to understand the wide world around her.\n"
                "Was there reason for her to try hard in high school? The only thing she lived for was summer vacation, where months of\n"
                "freedom from school waited for her. However, she was monitored even more during this period: parents randomly entering\n"
                "her room, baby cams, and repeated phone calls were common occurrences in this household. In Faiza's world, the place\n"
                "where her freedom came from was the bathroom.";
char ARTIST_intro_2[] =
                "Somewhere that didn't have cameras or eavesdroppers. Faiza couldn't explain why, but she bursted out in tears every\n"
                "time she entered the bathroom. She wasn't allowed to leave the house except if she had to attend an event she was forced\n"
                "to enter. Still, her parents monitored her moves. This was a rare chance for her to stare at the spacious skies, truly\n"
                "a scene that she admired and wanted to draw. It might have seemed as if Faiza was studying or competing, but her mind was\n"
                "trying to compute answers to the questions she had about purpose and life. These distracting thoughts clogged her brain.\n"
                "Weighed down by pressure, Faiza didn't do very well as a senior; it wasn't impressive to her parents at the very least.\n"
                "She resorted to cheating on tests to gain the trust of her parents again. This tactic worked out, and Faiza's acceptance\n"
                "into a top college was not rescinded. Her grades were outstanding, her involvement in clubs was impressive, her popularity\n"
                "was enough for her to have a couple of friends, her parents loved her, yet she was missing something critical in her life.\n"
                "She was made aware of this when she decorated her graduation cap with icons and drawings with her excited, proud parents.\n"
                "The graduation ceremony was wonderous; there was joy from accomplishment, yet there was lingering sadness from departure.\n"
                "When the entire class finished the diploma deliveries, Faiza ran away during the reunion ritual. You know, when the kids\n"
                "pour out of the auditorium looking for their loved ones. This part is always pure chaos incarnate, as you may know.";
char ARTIST_intro_3[] =
                "Anyway, the security was awful if Faiza was able to flee the scene. Who can blame them, though? Nobody expects a recent\n"
                "graduate to ditch their aspirations. I don't think so, at least. Faiza's parents grew worried, stressed, and panicked.\n"
                "They filed a search for a missing person, but it didn't pay off in the slightest. Faiza's parents searched high and low,\n"
                "close and far, for their beloved daughter. Where was she? Why did she suddenly disappear? Whose fault is it? These queries\n"
                "were glued to the parents' thoughts. If I had to tell you, I'd say Faiza left to confront her life, to live under the blue\n"
                "skies instead of a roof. Faiza went ahead and sold her graduation gown and cap to some no name and bought some canvases,\n"
                "a pretty feathered pen, and several colored ink canisters. Then, she drew based on her emotions and surrounding scenery.\n"
                "Passers-by would tip her with a coin or two sometimes, which would fund her art supplies. She would get suggestions and\n"
                "warnings. Faiza's goal was to draw uncensored art to show the world she didn't care about any \"petty\" restrictions.";
/* INDIA, MANY REGIONS, IRAN, CHINA, THAILAND, JAPAN, RUSSIA, S. KOREA, FRANCE, ISRAEL, BELARUS */
char ARTIST_intro_4[] =
                "She drew of a religious battle that ended up with violent killings. In another region, she drew of non-pornographic\n"
                "LGBT content between two persons. In another, she drew of an unveiled woman in the nude. In another, she drew of excessive\n"
                "government surveillance with a network of cameras. In another, she drew of a foot stepping on the country's currency.\n"
                "In another, she drew a detailed pornographic image with the genitalia fully revealed. In another, she drew the government\n"
                "killing off criticizing journalists. In another, she drew supportive propaganda for the other half of the nation. In\n"
                "another, she drew a pedophile and a naked child dangerously close to one another. In another, she drew of a crowd of\n"
                "citizens cheering on masked terrorists with firearms. In another, she drew of slaves with clown faces lined up to kiss\n"
                "a meager piece of paper. Faiza would finish her drawings and leave the canvases there for the citizens to view. Then,\n"
                "she would sneak into another nation or country through a border. Eventually, her parents broke down after the search\n"
                "for Faiza yielded NOTHING. They started blaming each other for not watching Faiza more closely. The argument took a\n"
                "tragic turn: the wife shot her husband multiple times with a handgun and then painstakingly shot herself. After years\n" 
                "of wandering, Matilda approached her and interested her with a flight to a different continent, where more censorship\n"
                "restrictions would await her.";
/* ACTOR-POLITICIAN. 
Key aspects:
- Melamine (maybe 50-100x) over the limit in Brazilian milk products + Used bribery
- Funded the sex trafficking group in the United States of America
- Invests into stocks, but he greeds out and loses tons of money
- Frequents brothel for drinks/sex action/gossip
- Goes broke from overspending 
- Invests -> Frequents brothel -> Funds gang -> Stocks crash -> Scandal -> Bankruptcy
*/
char POLITICIAN_intro_1[] =
                "Nicolau Leite. Age: 70 years.\n"
                "He was born to a film producer and an actress as a result of a one night stand. The producer proposed for the actress\n"
                "to go to another country to get an abortion, but she declined this proposition. Her feelings were mixed, but deep down,\n"
                "she wanted to be a mother. The producer gave in to her decision, but soon, he terminated communication and affiliation with\n"
                "the actress, not wanting to get involved with the baby. So, Nicolau was nurtured solely by his mother, who brought him to\n"
                "the theatre and studio when she couldn't look after him. These visits would push Nicolau to pursue an early career in acting.\n"
                "And so, Nicolau had an entry point into being a child actor. He practiced, rehearsed, and auditioned for shows and plays,\n"
                "getting offers at the age of 9 years old. Nicolau made a name for himself during his next couple of years in the industry\n"
                "and started lifting shortly afterward. He did this mainly for three reasons. The first was so that he could impress the\n"
                "ladies with his colossal muscles! The second was so that he could fill in for roles that required a fit male subject. The\n"
                "third was so that he could stay in shape. Nicolau was also inspired by other actors that were bodybuilders and successful.\n"
                "He landed roles in multiple trending movies. For example, he portrayed a minotaur in a world where mythical creatures were\n"
                "humanoid but humans were terrorizing beings. In another show, he portrayed the bouncer of a casino where human lives were\n"
                "the tokens used to call bets.";
char POLITICIAN_intro_2[] =
                "Viewers applauded his acting, noting his spacious range in roles. By record, he was the most popular actor in the country.\n"
                "The ladies loved him and fawned over his success as a strong actor. Nicolau didn't mind the attention but never entered a\n"
                "long-lasting relationship because his preferred type had to be accompanied with specific body measurements and race.\n"
                "Finding success with shaping his body, Nicolau would explore another field he was interested in. This field was politics.\n"
                "He jotted down a script for a speech that sounded inspiring and sure to get good ratings. Nicolau just emitted signs of\n"
                "a successful man, so the populace voted him in as the senator of his home state. During this period of pursuing a political\n"
                "position, Nicolau continued to take on key roles in movies and shows, but he also studied up on subjects like business and\n"
                "economy. After the popular ballot concluded, Nicolau was confirmed to have been voted in as a federal senator. He found\n"
                "success in meetings, congresses, and public hearings because of his extraordinary oratory skills. Nicolau didn't have time\n"
                "for acting anymore, so in his free time, he usually worked out or searched up for information about management roles.\n"
                "From the bottom of his heart, he wished to be a politician that voiced the general populace.";
char POLITICIAN_intro_3[] =
                "However, without his acting salary, Nicolau soon realized he wouldn't be able to make ends meet.\n"
                "The reason for this was because he was providing portions of his assets to his parents so they could live comfortably.\n"
                "Even though his father did not help in raising him, Nicolau was generous enough to help out his debt from crappy production.\n"
                "Nicolau needed a stack of money. He struck up a deal with a promising state-owned dairy products company that was in\n"
                "the red. In this deal, Nicolau would fund the company with a set amount of cash to invest into facilities, livestock, feed,\n"
                "and workers. In exchange, he would be provided a permanent cut of the company's income. The endangered company agreed to\n"
                "this partnership and took the startup money. However, this company invested most of this cash into melamine because it was\n"
                "cheap. When diluted milk is adulterated with melamine, it creates a facade of higher protein content, allowing the product\n"
                "an easier pass to quality control testing. Nicolau was informed of this strategy, and after deliberating about the trick,\n"
                "he concluded this was a solid plan based on the knowledge he gained from self-study. To assist with this, he slipped bribes\n"
                "to the quality checkers if the milk products were declined approval. Nobody that drank the milk products noticed anything\n"
                "wrong because only small volumes of melamine were added. Even so, these dairy products were toxic and posed a threat to\n"
                "the health of consumers. Melamine can cause kidney failure and kidney stones in living beings!";
char POLITICIAN_intro_4[] =
                "The scheme paid off. The quantity of the company's milk products increased, and shoppers bought the cheaper items like\n"
                "mad. As a result, Nicolau's wallet fattened up again. This cash was used to invest into the stock market, where Nicolau\n"
                "could profit enough to live comfortably as if he was an entire family. He hit up his tips and tricks from his self-study\n"
                "notes, and throughout the years, his value grew impressively. Along the way, Nicolau funded a sex trafficking gang that\n"
                "owned the best and biggest brothel in the country. Unexpectedly, that was where Nicolau found women who fit his criteria\n"
                "perfectly. Going to this brothel and ordering a worker was another one of Nicolau's free time activities. He would often\n"
                "shower his crushes with money, trying to win them over. That's right. Nicolau wanted these women all for himself, not for\n"
                "the public. By contract, the sex workers could not abandon their job or horrible things would happen to them. The persistent\n"
                "Nicolau donated to the higher-ups, hoping to overturn their terms of service. Nothing resulted from this. After this,\n"
                "he continued to fund the gang so that the brothel would stay in service and the women would be accessible. Years of these\n"
                "actions would follow until Matilda approached him with a proposition.";
char COP_intro_1[] =
                "Age: "
                "";